[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
key = "A"
mods = "Alt"
chars = "x1ba"

[[keyboard.bindings]]
key = "B"
mods = "Alt"
chars = "x1bb"

[[keyboard.bindings]]
key = "C"
mods = "Alt"
chars = "x1bc"

[[keyboard.bindings]]
key = "D"
mods = "Alt"
chars = "x1bd"

[[keyboard.bindings]]
key = "E"
mods = "Alt"
chars = "x1be"

[[keyboard.bindings]]
key = "F"
mods = "Alt"
chars = "x1bf"

[[keyboard.bindings]]
key = "G"
mods = "Alt"
chars = "x1bg"

[[keyboard.bindings]]
key = "H"
mods = "Alt"
chars = "x1bh"

[[keyboard.bindings]]
key = "I"
mods = "Alt"
chars = "x1bi"

[[keyboard.bindings]]
key = "J"
mods = "Alt"
chars = "x1bj"

[[keyboard.bindings]]
key = "K"
mods = "Alt"
chars = "x1bk"

[[keyboard.bindings]]
key = "L"
mods = "Alt"
chars = "x1bl"

[[keyboard.bindings]]
key = "M"
mods = "Alt"
chars = "x1bm"

[[keyboard.bindings]]
key = "N"
mods = "Alt"
chars = "x1bn"

[[keyboard.bindings]]
key = "O"
mods = "Alt"
chars = "x1bo"

[[keyboard.bindings]]
key = "P"
mods = "Alt"
chars = "x1bp"

[[keyboard.bindings]]
key = "Q"
mods = "Alt"
chars = "x1bq"

[[keyboard.bindings]]
key = "R"
mods = "Alt"
chars = "x1br"

[[keyboard.bindings]]
key = "S"
mods = "Alt"
chars = "x1bs"

[[keyboard.bindings]]
key = "T"
mods = "Alt"
chars = "x1bt"

[[keyboard.bindings]]
key = "U"
mods = "Alt"
chars = "x1bu"

[[keyboard.bindings]]
key = "V"
mods = "Alt"
chars = "x1bv"

[[keyboard.bindings]]
key = "W"
mods = "Alt"
chars = "x1bw"

[[keyboard.bindings]]
key = "X"
mods = "Alt"
chars = "x1bx"

[[keyboard.bindings]]
key = "Y"
mods = "Alt"
chars = "x1by"

[[keyboard.bindings]]
key = "Z"
mods = "Alt"
chars = "x1bz"

[[keyboard.bindings]]
key = "A"
mods = "Alt|Shift"
chars = "x1bA"

[[keyboard.bindings]]
key = "B"
mods = "Alt|Shift"
chars = "x1bB"

[[keyboard.bindings]]
key = "C"
mods = "Alt|Shift"
chars = "x1bC"

[[keyboard.bindings]]
key = "D"
mods = "Alt|Shift"
chars = "x1bD"

[[keyboard.bindings]]
key = "E"
mods = "Alt|Shift"
chars = "x1bE"

[[keyboard.bindings]]
key = "F"
mods = "Alt|Shift"
chars = "x1bF"

[[keyboard.bindings]]
key = "G"
mods = "Alt|Shift"
chars = "x1bG"

[[keyboard.bindings]]
key = "H"
mods = "Alt|Shift"
chars = "x1bH"

[[keyboard.bindings]]
key = "I"
mods = "Alt|Shift"
chars = "x1bI"

[[keyboard.bindings]]
key = "J"
mods = "Alt|Shift"
chars = "x1bJ"

[[keyboard.bindings]]
key = "K"
mods = "Alt|Shift"
chars = "x1bK"

[[keyboard.bindings]]
key = "L"
mods = "Alt|Shift"
chars = "x1bL"

[[keyboard.bindings]]
key = "M"
mods = "Alt|Shift"
chars = "x1bM"

[[keyboard.bindings]]
key = "N"
mods = "Alt|Shift"
chars = "x1bN"

[[keyboard.bindings]]
key = "O"
mods = "Alt|Shift"
chars = "x1bO"

[[keyboard.bindings]]
key = "P"
mods = "Alt|Shift"
chars = "x1bP"

[[keyboard.bindings]]
key = "Q"
mods = "Alt|Shift"
chars = "x1bQ"

[[keyboard.bindings]]
key = "R"
mods = "Alt|Shift"
chars = "x1bR"

[[keyboard.bindings]]
key = "S"
mods = "Alt|Shift"
chars = "x1bS"

[[keyboard.bindings]]
key = "T"
mods = "Alt|Shift"
chars = "x1bT"

[[keyboard.bindings]]
key = "U"
mods = "Alt|Shift"
chars = "x1bU"

[[keyboard.bindings]]
key = "V"
mods = "Alt|Shift"
chars = "x1bV"

[[keyboard.bindings]]
key = "W"
mods = "Alt|Shift"
chars = "x1bW"

[[keyboard.bindings]]
key = "X"
mods = "Alt|Shift"
chars = "x1bX"

[[keyboard.bindings]]
key = "Y"
mods = "Alt|Shift"
chars = "x1bY"

[[keyboard.bindings]]
key = "Z"
mods = "Alt|Shift"
chars = "x1bZ"

[[keyboard.bindings]]
key = "Space"
mods = "Control"
chars = "x00" # Ctrl + Space
