git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

  showFileTree:       true
  showListFooter:     false
  showRandomTip:      false
  showBottomLine:     false
  showCommandLog:     true
  showIcons:          true

disableStartupPopups: true
notARepository:       'skip'
os:
  editCommand:        'nvim'

