disableStartupPopups: true

gui:
    windowSize: 'normal'
    sidePanelWidth: 0.3333

git:
    paging:
        colorArg: always
        pager: delta --dark --paging=never

    showFileTree: true
    showListFooter: false
    showRandomTip: false
    showBottomLine: false
    showCommandLog: true
    showIcons: true

os:
  edit: 'myeditor {{filename}}'
  editAtLine: 'myeditor --line={{line}} {{filename}}'
  editAtLineAndWait: 'myeditor --block --line={{line}} {{filename}}'
  editInTerminal: true
