disableStartupPopups: true

gui:
    windowSize: 'normal'
    sidePanelWidth: 0.2

git:
    paging:
        colorArg: always
        pager: delta --dark --paging=never

    showFileTree: true
    showListFooter: false
    showRandomTip: false
    showBottomLine: false
    showCommandLog: true
    showIcons: true

os:
    openCommand: 'open {{filename}}'
    editCommand: 'nvim'
