#!/bin/bash

DISKLIST="$(diskutil list | tail -9 | awk '{print $5,$6,$8}' | awk -F 'HD' '{print $1,$2}' | awk -F '-' '{print $1, $2}' | awk '{$1=$1};1' | awk '{print $1}')"

HDDATA=$(echo "$DISKLIST" | head -3 | tail -1)
DATA=$(echo "$DISKLIST" | head -4 | tail -1)
PREEBOT=$(echo "$DISKLIST" | head -6 | tail -1)
VM=$(echo "$DISKLIST" | head -8 | tail -1)

REC=1

STORAGE=$(echo "$DISKLIST" | head -1 | sed 's/+//')
USAGE="$(awk -v h="$HDDATA" -v d="$DATA" -v p="$PREEBOT" -v v="$VM" 'BEGIN { print (h + d + p + v) }')"
CURRENT=$(awk -v u="$USAGE" -v s="$STORAGE" -v r="$REC" 'BEGIN { print (s - u - r) }')

echo "U:$USAGE | C:$CURRENT | S:$STORAGE"
