#!/bin/bash

DISKLIST="$(diskutil list | tail -9 | awk '{print $5,$6,$8}' | awk -F 'HD' '{print $1,$2}' | awk -F '-' '{print $1, $2}' | awk '{$1=$1};1' | awk '{print $1}')"
STORAGE=$(echo "$DISKLIST" | head -1 | sed 's/+//')
DISKUSAGE=$(echo "$DISKLIST" | tail -6 | awk '!seen[$1]++' | awk '{sum+=$1}END{print sum}')
CURRENTSPACE=$(echo "$STORAGE" "$DISKUSAGE" | awk '{print $1-$2}')
echo "U: $DISKUSAGE | C: $CURRENTSPACE"
