#!/bin/sh

# focus
cmd - j : yabai -m window --focus west
cmd - k : yabai -m window --focus east

# swap manage window
cmd + shift - j : yabai -m window --swap west
cmd + shift - k : yabai -m window --swap east

# disable shit macos
cmd - h:
cmd - m:
fn  - h:

# open brave
cmd + shift - return : open -a firefox

# open terminal
cmd - return : open -a alacritty

# fzf-menu
cmd + shift - f : /Applications/Alacritty.app/Contents/MacOS/alacritty --title="fzf-launcher" -e sh -c "$HOME/.local/share/fzf-launcher/fzf-launcher"

# toogle window into fullscreen
cmd - m : yabai -m window --toggle zoom-fullscreen

# float / unfloat window and center on screen
cmd + shift - m : yabai -m window --toggle float; \
          	  yabai -m window --grid 4:4:1:1:2:2

# miror
cmd + shift - s : yabai -m space --mirror y-axis

# destroy desktop
cmd + shift - w : yabai -m space --destroy

# create new desktop and follow focus
cmd + ctrl - n : yabai -m space --create && \
                 index="$(yabai -m query --spaces --display | jq 'map(select(."is-native-fullscreen" == false))[-1].index')" && \
                 yabai -m window --space "${index}" && \
                 yabai -m space --focus "${index}";

# move focus only desktop
cmd - 1 : yabai -m space --focus 1
cmd - 2 : yabai -m space --focus 2
cmd - 3 : yabai -m space --focus 3
cmd - 4 : yabai -m space --focus 4
cmd - 5 : yabai -m space --focus 5
cmd - 6 : yabai -m space --focus 6

# send window to desktop and follow focus
shift + cmd - 1 : yabai -m window --space  1; yabai -m space --focus 1
shift + cmd - 2 : yabai -m window --space  2; yabai -m space --focus 2
shift + cmd - 3 : yabai -m window --space  3; yabai -m space --focus 3
shift + cmd - 4 : yabai -m window --space  4; yabai -m space --focus 4
shift + cmd - 5 : yabai -m window --space  5; yabai -m space --focus 5
shift + cmd - 6 : yabai -m window --space  6; yabai -m space --focus 6

# reload yabai + skhd + status bar
cmd + shift - r : launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"; \
                  skhd --reload
