#!/bin/bash

# DISABLE SHIT MACOS
fn - h:

# open broweser
cmd + shift - return : open -a firefox

# open terminal
# cmd - return : open -a alacritty

# fzf-menu
cmd + shift - o : /Applications/Alacritty.app/Contents/MacOS/alacritty --title="fzf-launcher" -e sh -c "$HOME/.local/share/fzf-launcher/fzf-launcher"

# NAVIGATION
cmd - h : yabai -m window --focus west
cmd - j : yabai -m window --focus south
cmd - k : yabai -m window --focus north
cmd - l : yabai -m window --focus east

# MOVING WINDOW
shift + cmd - h : yabai -m window --warp west
shift + cmd - j : yabai -m window --warp south
shift + cmd - k : yabai -m window --warp north
shift + cmd - l : yabai -m window --warp east

# MOVE FOCUS SPACE DESKTOP
cmd - 1 : yabai -m space --focus 1
cmd - 2 : yabai -m space --focus 2
cmd - 3 : yabai -m space --focus 3
cmd - 4 : yabai -m space --focus 4
cmd - 5 : yabai -m space --focus 5

# SEND WINDOW TO DESKTOP AND FOLLOW FOCUS
shift + cmd - 1 : yabai -m window --space  1; yabai -m space --focus 1
shift + cmd - 2 : yabai -m window --space  2; yabai -m space --focus 2
shift + cmd - 3 : yabai -m window --space  3; yabai -m space --focus 3
shift + cmd - 4 : yabai -m window --space  4; yabai -m space --focus 4
shift + cmd - 5 : yabai -m window --space  5; yabai -m space --focus 5

# RESIZE WINDOWS
ctrl + cmd - h : yabai -m window west --resize right:-20:0 2> /dev/null || yabai -m window --resize right:-20:0
ctrl + cmd - j : yabai -m window north --resize bottom:0:20 2> /dev/null || yabai -m window --resize bottom:0:20
ctrl + cmd - k : yabai -m window south --resize top:0:-20 2> /dev/null || yabai -m window --resize top:0:-20
ctrl + cmd - l : yabai -m window east --resize left:20:0 2> /dev/null || yabai -m window --resize left:20:0

# ROTATE
alt - r         : yabai -m space --rotate 270
shift + alt - r : yabai -m space --rotate 90

# TOOGLE WINDOW INTO FULLSCREEN
cmd - m : yabai -m window --toggle zoom-fullscreen

# FLOAT / UNFLOAT WINDOW AND CENTER ON SCREEN
cmd + shift - m : yabai -m window --toggle float; \
          	  yabai -m window --grid 4:4:1:1:2:2

# MIROR
cmd + shift - s : yabai -m space --mirror y-axis

# DESTROY DESKTOP
cmd + shift - w : yabai -m space --destroy

# CREATE NEW DESKTOP AND FOLLOW FOCUS
cmd + ctrl - n : yabai -m space --create && \
                 index="$(yabai -m query --spaces --display | jq 'map(select(."is-native-fullscreen" == false))[-1].index')" && \
                 yabai -m window --space "${index}" && \
                 yabai -m space --focus "${index}";

# RELOAD YABAI + SKHD + STATUS BAR
cmd + shift - r : yabai --restart-service \
                  skhd --restart-service
