#!/bin/bash
FZF="fzf --reverse --inline-info"

VOCSTORE="$HOME/Documents/pd/data/vocabulary.txt"

MENU=$(
	echo -e "Add-Vocabulary\nFind-Vocabulary" |
		$FZF --prompt="Select opts > "
)

case $MENU in
	Add-Vocabulary)
		echo -e "add new word : \c"; read -r word
		echo -e "what the meaning of word : \c"; read -r mean
		if [ "$word" != "" ] && [ "$mean" != "" ]; then
			echo "word : $word | mean: $mean" >>"$VOCSTORE"
			echo "word : $word | mean: $mean successfully added 🌸"
		else
			echo "word and mean cannot be empty"
		fi
		;;
	Find-Vocabulary)
		(
			sed "" "$VOCSTORE" |
				$FZF --prompt="Find Vocabulary > " |
                pbcopy
		)
		;;
	*)
		echo "no menu selected"
		;;
esac
