#!/bin/bash

VOCSTORE="$HOME/Documents/data/vocabulary.txt"

MENU=$(
	echo -e "Add-Vocabulary\nFind-Vocabulary" |
		fzf --border=sharp --margin=0,1 --reverse --inline-info \
			--prompt="Select Menu > "
)

case $MENU in
	Add-Vocabulary)
		echo -e " add new word : \c"; read -r word
		echo -e " what the meaning of word : \c"; read -r mean
		if [ "$word" != "" ] && [ "$mean" != "" ]; then
			echo "word : $word | mean: $mean" >>"$VOCSTORE"
		else
			echo "word and mean cannot be empty"
		fi
		;;
	Find-Vocabulary)
		(
			sed "" "$VOCSTORE" |
				fzf --border=sharp --margin=0,1 --reverse --inline-info \
					--prompt="Select Vocabulacry > "
		)
		;;
	*)
		echo "no menu selected"
		;;
esac
