#!/bin/sh

sudo yabai --load-sa
yabai -m signal --add even=dock_did_restart action="sudo yabai --load-sa"

yabai -m config layout                          bsp
yabai -m config window_placement                second_child
yabai -m config window_origin_display           default
yabai -m config window_shadow                   float
yabai -m config focus_follows_mouse             off
yabai -m config mouse_follows_focus             on
yabai -m config window_topmost                  off
yabai -m config top_padding                     12
yabai -m config bottom_padding                  12
yabai -m config left_padding                    12
yabai -m config right_padding                   12
yabai -m config window_gap                      12
yabai -m config active_window_opacity           1.0
yabai -m config window_animation_duration       0.10
yabai -m config window_opacity_duration         0.10
yabai -m config window_opacity                  off
yabai -m config insert_feedback_color           0xFF282828
yabai -m config mouse_modifier                  fn
yabai -m config mouse_action1                   move
yabai -m config mouse_action2                   resize
yabai -m config mouse_drop_action               swap

# DEFAULT APP
yabai -m rule --add label="About This Mac" app="System Information" manage=off
yabai -m rule --add label="System Settings" app="^System Settings$" title=".*" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="Finder" app="^Finder" manage=off

# EXTEND APP
yabai -m rule --add label="karabiner-elements" app="^Karabiner-Elements" manage=off
yabai -m rule --add label="karabiner-event-viewer" app="^Karabiner-EventViewer" manage=off
yabai -m rule --add label="alt-tab" app="^AltTab" manage=off
yabai -m rule --add label="mvp" app="^mpv" manage=off
# yabai -m rule --add label="Music" app="^Music" manage=off
# yabai -m rule --add label="Skype" app="^Skype" manage=off

# RULES WINDOW
# yabai -m rule --add app="^(kitty|alacritty|terminal)$" space=1
# yabai -m rule --add app="^(Firefox|Safari)$" space=2
# yabai -m rule --add app="^(Whatsapp|Discord|Mail)$" space=3
# yabai -m rule --add app="^(Messages|FaceTime)$" space=4

# FZF-MENU
yabai -m rule --add title="fzf-launcher" manage=off
yabai -m rule --add app="Google Chrome" title="Picture in Picture" manage=off
yabai -m rule --add app="Brave Browser" title="Picture in Picture" manage=off

echo "yabai config loaded..🔥"
